version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ankitpokhrel
  - asciinema
  - atuin
  - awscli
  - awscurl
  - chsh
  - customfield
  - deno
  - devcontainer
  - direnv
  - dotfiles
  - funced
  - gitsign
  - httpie
  - markdownlint
  - nushell
  - passwordless
  - Rhum
  - runtimes
  - SCRIPTDIR
  - signin
  - sigstore
  - subl
  - taplo
  - topgrade
  - wslpath
  - zoxide
ignoreWords: []
import: []
